{{- if and .Values.loki.enabled .Values.loki.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.loki.serviceAccount.name }}
  namespace: {{ include "logging.namespace" . }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
    {{- include "loki.selectorLabels" . | nindent 4 }}
  {{- if or .Values.loki.serviceAccount.roleArn .Values.loki.serviceAccount.annotations }}
  annotations:
    {{- if .Values.loki.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.loki.serviceAccount.roleArn | quote }}
    {{- end }}
    {{- with .Values.loki.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
