{{- if and .Values.frontend.enabled .Values.frontend.config }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.frontend.name }}-config
  namespace: {{ include "stockwatch.namespace" . }}
  labels:
    {{- include "stockwatch.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.frontend.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}