{{- if and .Values.inventory.enabled .Values.inventory.config }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.inventory.name }}-config
  namespace: {{ include "stockwatch.namespace" . }}
  labels:
    {{- include "stockwatch.labels" . | nindent 4 }}
    {{- include "inventory.selectorLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.inventory.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
