kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.notifactions.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  PORT: {{ .Values.notifactions.configmap.data.PORT | quote}}                  
  HOST: {{ .Values.notifactions.configmap.data.HOST | quote}} 
  SMTP_PORT: {{ .Values.notifactions.configmap.data.SMTP_PORT | quote}} 
  SMTP_FROM: {{ .Values.notifactions.configmap.data.SMTP_FROM | quote}} 
